apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  project: homelab
  sources:
    - repoURL: quay.io/jetstack/charts
      chart: cert-manager
      targetRevision: v1.19.2
      helm:
        valueFiles:
          - $values/charts/cert-manager/values.yaml
    - repoURL: https://github.com/mjprobinson/homelab
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/mjprobinson/homelab
      path: manifests/cert-manager
      targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
