apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-nfs
  namespace: csi-driver-nfs
spec:
  project: homelab
  sources:
    - repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
      chart: csi-driver-nfs
      targetRevision: 4.13.1
      helm:
        valueFiles:
          - $values/charts/csi-driver-nfs/values.yaml
    - repoURL: https://github.com/mjprobinson/homelab
      targetRevision: HEAD
      ref: values
  destination:
    name: in-cluster
    namespace: csi-driver-nfs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
