apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ddns-updater
  namespace: ddns-updater
spec:
  project: homelab
  sources:
    - repoURL: https://github.com/mjprobinson/homelab
      path: manifests/ddns-updater
      targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: ddns-updater
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
